language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - python --version
  - pip --version
  # command to install dependencies
  - pip install cython wget
  - pip install coveralls coverage codeclimate-test-reporter
  - pip install .
# command to run tests
script:
  - coverage run --include=htrc/* setup.py test
  - coverage report
after_success:
  - coveralls
  - codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 0299da27c6ac280129992725e48ee5ff71ea668b755a0301ebd8374c6900b80e
